get-appxpackage -allusers *messaging* | remove-appxpackage
get-appxpackage -allusers *sway* | remove-appxpackage
get-appxpackage -allusers *commsphone* | remove-appxpackage
get-appxpackage -allusers *windowsphone* | remove-appxpackage
get-appxpackage -allusers *phone* | remove-appxpackage
get-appxpackage -allusers *communicationsapps* | remove-appxpackage
get-appxpackage -allusers *people* | remove-appxpackage
get-appxpackage -allusers *zune* | remove-appxpackage
get-appxpackage -allusers *zunemusic* | remove-appxpackage
get-appxpackage -allusers *zunevideo* | remove-appxpackage
get-appxpackage -allusers *bingfinance* | remove-appxpackage
get-appxpackage -allusers *bingnews* | remove-appxpackage
get-appxpackage -allusers *bingsports* | remove-appxpackage
get-appxpackage -allusers *bingweather* | remove-appxpackage
get-appxpackage -allusers *bing* | remove-appxpackage
get-appxpackage -allusers *onenote* | remove-appxpackage
get-appxpackage -allusers *alarms* | remove-appxpackage
get-appxpackage -allusers *camera* | remove-appxpackage
get-appxpackage -allusers *photos* | remove-appxpackage
get-appxpackage -allusers *maps* | remove-appxpackage
get-appxpackage -allusers *soundrecorders* | remove-appxpackage
get-appxpackage -allusers *xbox* | remove-appxpackage
get-appxpackage -allusers *solitaire* | remove-appxpackage
get-appxpackage -allusers *officehub* | remove-appxpackage
get-appxpackage -allusers *skypeapp* | remove-appxpackage
get-appxpackage -allusers *getstarted* | remove-appxpackage
get-appxpackage -allusers *3d* | remove-appxpackage
get-appxpackage -allusers *3dbuilder* | remove-appxpackage
get-appxpackage -allusers *windowsstore* | remove-appxpackage
